### ISSUE TITLE
Gradients example?

### ISSUE THREAD

**Issue by deadcoder0904** [omgovich/react-colorful#113] opened 2021-02-23 06:25 UTC
I would love to add Gradients to my app but I'm not sure how to do that 🤔

Is this possible with `react-colorful`? If so, any examples?

**Comment by omgovich** [comment] 2021-02-23 06:51
Hi! Do you have any mockup of the UI you're developing?

**Comment by deadcoder0904** [comment] 2021-02-23 06:52
Nope. But I might just replicate the UI from Sketch or Figma only 👍

**Comment by omgovich** [comment] 2021-02-24 14:12
Are you looking for something like this?
https://codesandbox.io/s/react-colorful-gradient-qovjy

**Comment by deadcoder0904** [comment] 2021-02-25 08:17
I'm not really sure about the UI but I'll definitely ask if I don't get it. Usually I want to incorporate it in the same UI as below:

![image](https://user-images.githubusercontent.com/16436270/109123180-8caaa180-776f-11eb-8b25-fe148ef4e15c.png)

But this is actually brilliant. Just use the same picker with 2 squares to change the color. I'll take a look at Sketch or Figma & see how they've implemented & give it a shot. Will get back to you in a couple of days 👍

**Comment by omgovich** [comment] 2021-02-25 08:50
I close the issue if you don't mind (since it's actually not a picker's issue), but we can continue the discussion here.

**Closed by omgovich** 2021-02-25 08:50 UTC

**Comment by deadcoder0904** [comment] 2021-03-25 11:53
Hey, @omgovich finally gotten around it. I want it to be like Sketch's Color Picker because Figma's Color Picker sucks badly.

This is how it should look:

![sketch color picker](https://user-images.githubusercontent.com/16436270/112466761-350e4e80-8d8c-11eb-81e8-9cad2d3ced8f.png)

I want to make the 2 notches & if I click in the middle a 3rd one pops-up & another click brings the 4th one & so on...

Would love to have an idea of how to go about the pointers moving along?

**Comment by omgovich** [comment] 2021-03-30 09:52
Oh, the task isn't easy)
I'll try to create a code recipe once I have enough time 👌

**Comment by deadcoder0904** [comment] 2021-03-30 11:08
@omgovich Yeah, whenever. I did try but that got really hard. Will keep trying though :)

**Comment by deadcoder0904** [comment] 2021-04-23 10:14
Hey, @omgovich any updates on this? A little bit of guidance would be helpful if you don't have time.

**Comment by omgovich** [comment] 2021-04-23 11:29
Hi! Was super busy (participating in a JS-conference organization and with my new Colord project).
Will try to create a code draft soon.

**Comment by omgovich** [comment] 2021-04-23 13:26
Basic mechanic (dragging and deleting is not present):
https://codesandbox.io/s/react-colorful-gradient-forked-luc5l?file=/src/App.js

**Comment by deadcoder0904** [comment] 2021-04-23 13:32
That's lovely. I believe dragging & deleting should be simple, right? If so, any clues in the current codebase? I'll try implementing it.

And thank you once again. Your support is amazing.

**Comment by omgovich** [comment] 2021-04-23 13:35
Deleting should be simple. Regarding the point dragging — I guess you can try to copy the code from this repo (see `Interactive.tsx`).

**Comment by deadcoder0904** [comment] 2021-04-26 09:43
I saw you're setting a new color stop to `#000000` by default. Can we somehow make sure it sets to the color on which we clicked on?

**Comment by omgovich** [comment] 2021-04-26 11:55
You need somethimg like `tinycolor.mix(color1, color2, amount = 50)` for that I guess.

**Comment by deadcoder0904** [comment] 2021-04-27 07:31
Thank you, that was pretty simple:

```ts
import tinycolor from 'tinycolor2'

const newColor = tinycolor.mix(colorsCopy[afterIndex - 1], colorsCopy[afterIndex], position)
colorsCopy.splice(afterIndex, 0, newColor.toHexString())
```

**Comment by deadcoder0904** [comment] 2021-04-28 11:59
So I needed `alpha` value in picker so I switched from `HexColorPicker` to `RgbaColorPicker`.

However, when I click on the `linear-gradient` bar, it doesn't move the color in the big middle thing. It shows the correct color on the bar itself.

Only thing I've done here is added 2 functions & changed 2 lines. Here's the Codesandbox → https://codesandbox.io/s/react-colorful-linear-gradient-rgba-y1mdm?file=/src/App.js

Anything I'm doing wrong?

**Comment by omgovich** [comment] 2021-04-28 14:42
Fells like the problem is in `bg2rgb` function.
I would recommend droping this function and replace `RgbaColorPicker` with `RgbaStringColorPicker`.

**Comment by deadcoder0904** [comment] 2021-04-29 02:52
Thanks again, that was really simple. I didn't see the table in the docs at all otherwise I'd never have used `RgbaColorPicker`. `RgbaStringColorPicker` is more simpler :)

**Comment by elie222** [comment] 2022-07-26 14:49
> https://gradient-package-demo.web.app/

Cool example. Another project that can help people looking for gradient support is: https://gradient-package-demo.web.app/
